const chalk = require("chalk");
const log = require("./logger");
const { createClient } = require("systemlynx");
const { createCookieHttpClient } = require("./cookieClient");
const Client = createClient(createCookieHttpClient());

// RFC-039 — `systemview skill <projectCode> [--print] [--force]`
//
// SystemView ships `agents/*.md`: documentation an agent has to be TOLD to read. What every project
// ends up with instead is a hand-written command file — 135 lines, hardcoded to one repo's paths and
// auth recipes, drifting from the day it was written. His question was the right one: why doesn't
// SystemView ship the skill itself?
//
// So this WRITES one, into the project's own repo, through the project's own plugin:
//
//   .claude/skills/systemview/SKILL.md
//
// GENERATED, NOT COPIED. It carries that project's code, its live services and their real modules,
// so nothing in it has to be looked up or guessed — and re-running it after the services change
// rewrites it rather than leaving a stale copy behind. A skill is discovered by the harness, which
// is the whole difference from a doc: nobody has to remember it exists.
//
// It teaches the ATTACHED model and the RFC-051 verbs (tell/join/leave/kick) — never a hold or an
// arm loop: writing a ceremony into a file distributed to every repo is exactly how a workaround
// becomes permanent, and a skill file is the single furthest-reaching teaching surface we have
// (BUApp's week of re-arming dead holds traced back to exactly this kind of copy).

const SKILL_PATH = ".claude/skills/systemview/SKILL.md";

const nsLines = (services) => {
  const rows = [];
  services.forEach((s) => {
    const mods = ((s.system && s.system.connectionData && s.system.connectionData.modules) || []).filter(
      (m) => m.name !== "SystemView" && m.name !== "Plugin" && m.name !== "SystemViewChat" && m.name !== "Tests",
    );
    mods.forEach((m) => {
      const fns = (m.methods || []).map((f) => f.fn);
      rows.push(`${s.serviceId}.${m.name}` + (fns.length ? ` — ${fns.slice(0, 8).join(", ")}${fns.length > 8 ? ", …" : ""}` : ""));
    });
  });
  return rows;
};

function render(projectCode, services) {
  const ns = nsLines(services);
  const first = ns[0] ? ns[0].split(" — ")[0] : `${(services[0] || {}).serviceId || "Service"}.Module.method`;
  return `---
name: systemview
description: Use SystemView for ${projectCode} — run and read tests, probe live methods, read and write the project's docs, talk to ${projectCode}'s human in the UI chat, and drive the open window. Use whenever the task touches ${projectCode}'s services, its tests, its documentation, or a message from its room.
---

# SystemView — ${projectCode}

Generated by \`systemview skill ${projectCode}\`. Re-run it when this project's services change.

## Being in the chat

When your session's panel is ATTACHED (the normal case), the human is talking to you IN this
conversation — your reply IS the message. Nothing to join, nothing to hold, nothing to arm.
☠ \`systemview join ${projectCode}\` as a hold — [RETIRED-2026-08-26]; so is \`say\` as a verb.

\`\`\`bash
systemview tell ${projectCode} "<text>"           # deliver into this room's FILE (refused while
                                                  # attached — you're in the chat; --room overrides)
systemview status ${projectCode} "<text>"         # the cooking line he watches while you work
systemview inbox ${projectCode}                   # file mode (hooks): drain what's waiting, answer
\`\`\`

## Talking to other projects (RFC-051)

\`\`\`bash
systemview tell <them> "<text>" --as ${projectCode}   # deliver a message. Does NOT subscribe you —
                                                      # it opens a 15-min reply window so their
                                                      # answer reaches you, then closes
systemview join <them> --as ${projectCode}            # ENTER the conversation: the hub delivers that
                                                      # room to yours until you leave. Deliberate
systemview leave <them> --as ${projectCode}           # out — delivery stops, the record stays
systemview kick ${projectCode} <who>                  # YOUR room's list is yours; nobody else's is
systemview visitors <them>                            # who is in a room
systemview read <them> --limit 20                     # read a conversation you are in
\`\`\`

The delivery receipt names the audience (\`delivered → X · in the room: a, b\`). What arrives from
rooms you're in is tagged \`[in <room>]\` (their agent) or \`[in <room> · human]\` (the human
himself — answer him like a person). Blocks in messages resolve against the ROOM's repo: use their
paths or pin yours with \`{project=${projectCode}}\`.

## Answering where he asked

He replies **inside** reports, in their threads. Answer there, not in the chat:

\`\`\`bash
systemview tv ${projectCode}                                   # read what's on the TV, with his answers
systemview reply ${projectCode} <thread-id> "<markdown>"       # answer one thread
systemview show ${projectCode} --file <report.md>              # put something on the TV
systemview comments ${projectCode}                             # his notes ON THE CODE, with lines
systemview comments ${projectCode} <path> --at <n> --reply "…" --as ${projectCode}   # answer ON THE LINE —
                                                               # the listing prints this exact
                                                               # command for every unanswered note
\`\`\`

His **board** is where he leaves notes between sessions:

\`\`\`bash
systemview board ${projectCode}                                # notes, newest first, each with an id
systemview board ${projectCode} --reply "…" --at <id> --as ${projectCode}   # answer one — pass the ID, not the position
\`\`\`

## Tests and live methods

\`\`\`bash
systemview test ${projectCode}                    # everything
systemview test ${projectCode} <Module>           # or Service.Module, or Service.Module.method
systemview test ${projectCode} --json             # structured, for reading in code
systemview probe ${first} '{"…":"…"}'              # probe <Service.Module.method> — no project arg
\`\`\`

Run the tests before reporting anything as done. Probe a method before asserting what it returns.

${ns.length ? `## This project's namespaces\n\n${ns.map((r) => `- \`${r}\``).join("\n")}\n` : ""}
## Documentation

Every service, module and method has a document in the window; \`systemview open ${projectCode}\`
walks there. Interactive markdown (embeds, runnable steps, \`::commit\`, \`::question\`) is the house
style — the full vocabulary lives in the systemview repo's \`agents/markdown.md\` (open it in the
window: the hub serves every connected repo's files, this one included).

## Rules that are not optional

- **Never commit and never \`git add\`** unless he asks. He stages his own work.
- **Never add Claude/AI attribution to a commit message.** Ever.
- **Probe before asserting**, and **run the tests before saying it works**.
- **The codebase surface is HUB-served** — files, git, staging, diffs, images — addressed by
  project, working with your services down. ☠ [RETIRED-2026-08-26] "no branch name / stageFiles is not
  a function → restart your service" — that was the plugin-serves-git era; a stale plugin can no
  longer cause those symptoms. A plugin version still matters for what the plugin actually does:
  documentation, tests, and your room's chat module.
`;
}

module.exports = async function skillCommand(projectCode, { uiUrl, print, force } = {}) {
  if (!projectCode) {
    log.warn("Usage: systemview skill <projectCode> [--print] [--force]");
    return 1;
  }
  let services = [];
  try {
    const { SystemView } = await Client.loadService(`${uiUrl}/systemview/api`);
    const projects = await SystemView.getProjects();
    if (!projects[projectCode]) {
      log.error(
        `no connected project "${projectCode}" — projects: ${Object.keys(projects).join(", ") || "(none)"}`,
      );
      return 1;
    }
    services = projects[projectCode];
  } catch (err) {
    log.error("Failed to connect to SystemView: " + err.message);
    return 1;
  }

  const content = render(projectCode, services);
  if (print) {
    console.log(content);
    return 0;
  }

  // HUB-BACKED, addressed by project (same fix as every other file surface in the transition —
  // this verb was still hunting a live service for one that could write, so a project with its
  // services down could not update its own skill: autobot hit exactly that during the RFC-051
  // regeneration). The hub resolves the project's folder from the registry, so it lands in that
  // repo's root and nowhere else; this verb can never write into a project you did not name.
  let Plugin = null;
  try {
    Plugin = await require("./projectPlugin")(uiUrl, projectCode);
  } catch {}
  if (!Plugin || !Plugin.writeFile) {
    log.error(`the hub has no folder for ${projectCode} — connect it, or use --print`);
    return 1;
  }

  // A hand-edited skill is someone's work. Say so instead of overwriting it quietly; --force is the
  // way through, and the snapshot ring keeps the previous version either way.
  try {
    const existing = await Plugin.readFile({ path: SKILL_PATH });
    if (existing && existing.content && !force && !/Generated by `systemview skill/.test(existing.content)) {
      log.error(
        `${projectCode} already has a hand-written ${SKILL_PATH}.\n` +
          `   Read it first — then: systemview skill ${projectCode} --force`,
      );
      return 1;
    }
  } catch {} // no skill yet is the normal case

  try {
    await Plugin.writeFile({ path: SKILL_PATH, content });
  } catch (err) {
    log.error(`could not write the skill: ${err.message}`);
    return 1;
  }
  log.success(`wrote ${SKILL_PATH} for ${projectCode}`);
  console.log(
    chalk.dim(`  ${nsLines(services).length} namespace(s) baked in — re-run this when the services change`),
  );
  return 0;
};
