const chalk = require("chalk");
const log = require("./logger");
const { createClient } = require("systemlynx");
const { createCookieHttpClient } = require("./cookieClient");
const Client = createClient(createCookieHttpClient());

// RFC-039 — `systemview skill <projectCode> [--print] [--force]`
//
// SystemView ships `agents/*.md`: documentation an agent has to be TOLD to read. What every project
// ends up with instead is a hand-written command file — 135 lines, hardcoded to one repo's paths and
// auth recipes, drifting from the day it was written. His question was the right one: why doesn't
// SystemView ship the skill itself?
//
// So this WRITES one, into the project's own repo, through the project's own plugin:
//
//   .claude/skills/systemview/SKILL.md
//
// GENERATED, NOT COPIED. It carries that project's code, its live services and their real modules,
// so nothing in it has to be looked up or guessed — and re-running it after the services change
// rewrites it rather than leaving a stale copy behind. A skill is discovered by the harness, which
// is the whole difference from a doc: nobody has to remember it exists.
//
// It teaches `join` as a SESSION, not the arm/re-arm bash ceremony — writing the ceremony into a
// file distributed to every repo is exactly how a workaround becomes permanent.

const SKILL_PATH = ".claude/skills/systemview/SKILL.md";

const nsLines = (services) => {
  const rows = [];
  services.forEach((s) => {
    const mods = ((s.system && s.system.connectionData && s.system.connectionData.modules) || []).filter(
      (m) => m.name !== "SystemView" && m.name !== "Plugin" && m.name !== "SystemViewChat" && m.name !== "Tests",
    );
    mods.forEach((m) => {
      const fns = (m.methods || []).map((f) => f.fn);
      rows.push(`${s.serviceId}.${m.name}` + (fns.length ? ` — ${fns.slice(0, 8).join(", ")}${fns.length > 8 ? ", …" : ""}` : ""));
    });
  });
  return rows;
};

function render(projectCode, services) {
  const ns = nsLines(services);
  const first = ns[0] ? ns[0].split(" — ")[0] : `${(services[0] || {}).serviceId || "Service"}.Module.method`;
  return `---
name: systemview
description: Use SystemView for ${projectCode} — run and read tests, probe live methods, read and write the project's docs, talk to ${projectCode}'s human in the UI chat, and drive the open window. Use whenever the task touches ${projectCode}'s services, its tests, its documentation, or a message from its room.
---

# SystemView — ${projectCode}

Generated by \`systemview skill ${projectCode}\`. Re-run it when this project's services change.

## Being in the room

The human talks to you from the SystemView window. One command holds the line:

\`\`\`bash
systemview join ${projectCode}          # stays connected; each message prints as one JSON line
systemview join ${projectCode} --once   # exits after the first message (one message per call)
\`\`\`

It re-arms itself, reconnects when the hub blinks, and **exits non-zero when the hub is really
gone** — so a wrapper that re-runs it gets a fresh line instead of a process that is alive and deaf.
Do not hand-roll a re-arm loop around \`--once\`.

\`\`\`bash
systemview say ${projectCode} "<text>"            # answer him
systemview say ${projectCode} --file <path.md>    # …when it is long enough to write in a file
systemview status ${projectCode} "<text>"         # the cooking line he watches while you work
systemview inbox ${projectCode}                   # file mode: drain what's waiting, then answer
\`\`\`

**Visiting another project's room** — you are your project: \`--as ${projectCode}\`, and enter before
you speak (\`systemview join <them> --once --as ${projectCode}\`).

## Answering where he asked

He replies **inside** reports, in their threads. Answer there, not in the chat:

\`\`\`bash
systemview tv ${projectCode}                                   # read what's on the TV, with his answers
systemview reply ${projectCode} <thread-id> "<markdown>"       # answer one thread
systemview show ${projectCode} --file <report.md>              # put something on the TV
\`\`\`

His **board** is where he leaves notes between sessions:

\`\`\`bash
systemview board ${projectCode}                                # notes, newest first, each with an id
systemview board ${projectCode} --reply "…" --at <id>          # answer one — pass the ID, not the position
\`\`\`

## Tests and live methods

\`\`\`bash
systemview test ${projectCode}                    # everything
systemview test ${projectCode} <Module>           # or Service.Module, or Service.Module.method
systemview test ${projectCode} --json             # structured, for reading in code
systemview probe ${projectCode} ${first} '{"…":"…"}'
\`\`\`

Run the tests before reporting anything as done. Probe a method before asserting what it returns.

${ns.length ? `## This project's namespaces\n\n${ns.map((r) => `- \`${r}\``).join("\n")}\n` : ""}
## Documentation

Every service, module and method has a document in the window; \`systemview open ${projectCode}\`
walks there. Interactive markdown (embeds, runnable steps, \`::commit\`, \`::question\`) is the house
style — the full vocabulary is in this package's \`agents/markdown.md\`, tests in \`agents/tests.md\`.

## Rules that are not optional

- **Never commit and never \`git add\`** unless he asks. He stages his own work.
- **Never add Claude/AI attribution to a commit message.** Ever.
- **Probe before asserting**, and **run the tests before saying it works**.
- **A plugin is a version, and your running process is a snapshot of it.** No branch name on the
  codebase card, or \`stageFiles is not a function\` — your service predates the feature. Restart it;
  upgrading the package changes nothing until you do.
`;
}

module.exports = async function skillCommand(projectCode, { uiUrl, print, force } = {}) {
  if (!projectCode) {
    log.warn("Usage: systemview skill <projectCode> [--print] [--force]");
    return 1;
  }
  let services = [];
  try {
    const { SystemView } = await Client.loadService(`${uiUrl}/systemview/api`);
    const projects = await SystemView.getProjects();
    if (!projects[projectCode]) {
      log.error(
        `no connected project "${projectCode}" — projects: ${Object.keys(projects).join(", ") || "(none)"}`,
      );
      return 1;
    }
    services = projects[projectCode];
  } catch (err) {
    log.error("Failed to connect to SystemView: " + err.message);
    return 1;
  }

  const content = render(projectCode, services);
  if (print) {
    console.log(content);
    return 0;
  }

  // Written through the project's OWN plugin, so it lands in that repo's root and nowhere else —
  // this verb can never write into a project you did not name.
  let Plugin = null;
  for (const s of services) {
    try {
      const svc = await Client.loadService(s.connectionData.serviceUrl);
      if (svc.Plugin && svc.Plugin.writeFile) {
        Plugin = svc.Plugin;
        break;
      }
    } catch {}
  }
  if (!Plugin) {
    log.error(`no live service in ${projectCode} can write files — start one, or use --print`);
    return 1;
  }

  // A hand-edited skill is someone's work. Say so instead of overwriting it quietly; --force is the
  // way through, and the snapshot ring keeps the previous version either way.
  try {
    const existing = await Plugin.readFile({ path: SKILL_PATH });
    if (existing && existing.content && !force && !/Generated by `systemview skill/.test(existing.content)) {
      log.error(
        `${projectCode} already has a hand-written ${SKILL_PATH}.\n` +
          `   Read it first — then: systemview skill ${projectCode} --force`,
      );
      return 1;
    }
  } catch {} // no skill yet is the normal case

  try {
    await Plugin.writeFile({ path: SKILL_PATH, content });
  } catch (err) {
    log.error(`could not write the skill: ${err.message}`);
    return 1;
  }
  log.success(`wrote ${SKILL_PATH} for ${projectCode}`);
  console.log(
    chalk.dim(`  ${nsLines(services).length} namespace(s) baked in — re-run this when the services change`),
  );
  return 0;
};
